### PR TITLE
Update submodule and patchset

### PR DESCRIPTION
**Pull request by xhaihao**
Update 0022, 0085-0090

Submodule ffmpeg 802d2d1f02..f6d8464590

### CODE REVIEW

**Comment by xhaihao** [comment]
@tong1wu  could you have a look at this change ?

**Comment by tong1wu** [comment]
https://github.com/FFmpeg/FFmpeg/commit/e35dfe864d8fb1ee9e28684a5a93e4b75d0d8092#diff-152a17af0a4a8960c38788005bd146970fde1e9371e761e996b414748c17a60eR441 I think we should modify the hwaccel structures like this.

**Comment by xhaihao** [comment]
> [FFmpeg/FFmpeg@e35dfe8#diff-152a17af0a4a8960c38788005bd146970fde1e9371e761e996b414748c17a60eR441](https://github.com/FFmpeg/FFmpeg/commit/e35dfe864d8fb1ee9e28684a5a93e4b75d0d8092#diff-152a17af0a4a8960c38788005bd146970fde1e9371e761e996b414748c17a60eR441) I think we should modify the hwaccel structures like this.

Thanks for pointing it out, fixed in the new version

**Comment by xhaihao** [comment]
The error in pre-check is not caused by this PR

**Pull request merged**
