### PR TITLE
Update submodule and patchsets

### PR DESCRIPTION
**Pull request by xhaihao**
Submodule ffmpeg 0ecc1f0e48..8b76bae896

Updated 0073, 0074, 0094, 0121
Deleted 0119, 0120

### CODE REVIEW

**Comment by xhaihao** [comment]
@wenbinc-Bin  @tong1wu could you help to review this PR ?

**Comment by tong1wu** [comment]
LGTM

**Comment by wenbinc-Bin** [comment]
LGTM Thanks

**Comment by xhaihao** [comment]
The error in pre-check should be caused by FFmmpeg master. @uartie @Bin-CI

**Pull request merged**
