### PR TITLE
Update submodule and patchsets

### PR DESCRIPTION
**Pull request by xhaihao**
Submodule ffmpeg 0ecc1f0e48..85b8d59ec7

Updated 0094, 0121
Deleted 0119, 0120

### CODE REVIEW

**Comment by xhaihao** [comment]
@wenbinc-Bin  @tong1wu could you help to review this PR ? thx

**Comment by wenbinc-Bin** [comment]
LGTM, thanks.

**Comment by tong1wu** [comment]
LGTM

**Comment by xhaihao** [comment]
@Bin-CI The error in pre-check was not caused by this PR.

**Comment by xhaihao** [comment]
> @xhaihao please help for fix issue like on encode/avc ffmpeg-qsv
> 
> ```
> DEBUG: slash: [graph 0 input from stream 0:0 @ 0x7fc740004800] w:720 h:480 pixfmt:yuv420p tb:1/30 fr:30/1 sar:0/1 csp:unknown range:unknown
> DEBUG: slash: [auto_scale_0 @ 0x7fc740008380] w:iw h:ih flags:'' interl:0
> DEBUG: slash: [Parsed_format_0 @ 0x7fc740003780] auto-inserting filter 'auto_scale_0' between the filter 'graph 0 input from stream 0:0' and the filter 'Parsed_format_0'
> ```
> 
> ffmpeg-vaapi
> 
> ```
> DEBUG: slash: [graph 0 input from stream 0:0 @ 0x7f2848004340] w:720 h:480 pixfmt:yuv420p tb:1/30 fr:30/1 sar:0/1 csp:unknown range:unknown
> DEBUG: slash: [auto_scale_0 @ 0x7f2848007d40] w:iw h:ih flags:'' interl:0
> DEBUG: slash: [Parsed_format_0 @ 0x7f28480034c0] auto-inserting filter 'auto_scale_0' between the filter 'graph 0 input from stream 0:0' and the filter 'Parsed_format_0'
> ```

The first bad commit is http://git.videolan.org/?p=ffmpeg.git;a=commit;h=8c7934f73ab6c568acaa47c821a6833f9145fdbb

**Pull request merged**
