### PR TITLE
patches: Remove SCC decode patches which upstreamed

### PR DESCRIPTION
**Pull request by feiwan1**

### CODE REVIEW

**Review by xhaihao — APPROVED** [review]
LGTM

**Comment by uartie** [comment]
@feiwan1 one SCC case is failing... please check it.

**Comment by feiwan1** [comment]
Hi @uartie, There was some WA code which I didn't submit that into ffmepg community. The WA code can decode "SCC High Throughput 444 14" profile by using "SCC" profile. I have also talked to @FocusLuo to see if we can remove this case from our test.

**Comment by uartie** [comment]
> Hi @uartie, There was some WA code which I didn't submit that into ffmepg community. The WA code can decode "SCC High Throughput 444 14" profile by using "SCC" profile. I have also talked to @FocusLuo to see if we can remove this case from our test.

I will disable the test in BAT/pre-check for now.  Let me know when/if we need to add it back.  We can put it in SANITY/FULL until @FocusLuo confirms requirement.

**Comment by uartie** [comment]
@feiwan1 I see ffmpeg emits this warning:
```
SCC profile is not yet implemented in hevc native decoder.
```
and
```
high_precision_offsets_enabled_flag not yet implemented
```

Are these expected?

**Comment by uartie** [comment]
> > Hi @uartie, There was some WA code which I didn't submit that into ffmepg community. The WA code can decode "SCC High Throughput 444 14" profile by using "SCC" profile. I have also talked to @FocusLuo to see if we can remove this case from our test.
> 
> I will disable the test in BAT/pre-check for now. Let me know when/if we need to add it back. We can put it in SANITY/FULL until @FocusLuo confirms requirement.

What is the plan to add support for `SCC High Throughput 444 14` profile in ffmpeg-vaapi?  It is supported in ffmpeg-qsv and gstreamer.

**Comment by feiwan1** [comment]
> @feiwan1 I see ffmpeg emits this warning:
> 
> ```
> SCC profile is not yet implemented in hevc native decoder.
> ```
> 
> and
> 
> ```
> high_precision_offsets_enabled_flag not yet implemented
> ```
> 
> Are these expected?

Yes, the warning shows in parser of hevc scc, to tell user scc and related feature is not implemented in native software decoder. Otherwise if user use native decoder, the cmdline excute without any warning but the result may incorrect.

**Comment by feiwan1** [comment]
> > > Hi @uartie, There was some WA code which I didn't submit that into ffmepg community. The WA code can decode "SCC High Throughput 444 14" profile by using "SCC" profile. I have also talked to @FocusLuo to see if we can remove this case from our test.
> > 
> > 
> > I will disable the test in BAT/pre-check for now. Let me know when/if we need to add it back. We can put it in SANITY/FULL until @FocusLuo confirms requirement.
> 
> What is the plan to add support for `SCC High Throughput 444 14` profile in ffmpeg-vaapi? It is supported in ffmpeg-qsv and gstreamer.

We can support it if libva add the "SCC High Throughput 444 14" profile entry which defines in hevc spec A3.8(SCC defines in A3.7). There should be samilar WA in QSV/VPL as what we did for ffmepg-vaapi before.

**Pull request merged**
